(in-package #:website)

(defparameter *sitedir* "/Users/deepaksurti/wwwc/")
(defparameter *sitehtmldir* "/Users/deepaksurti/www/")
(defparameter *siteintdir* "/Users/deepaksurti/www-int/")
(defparameter *siteextras* "/Users/deepaksurti/www-extras/")
(defparameter *author* "Deepak Surti")
(defparameter *email* "dmsurti@gmail.com")
(defparameter *sitename* "Deepak Surti's website")
(defparameter *dict* nil)
